### ISSUE TITLE
Apex Execute fails: SOAP-ERROR: Encoding: object has no 'uiRequestId' property

### ISSUE THREAD

**Issue by diligent176** [forceworkbench/forceworkbench#665]
Since recently (a couple weeks), I can't execute anonymous apex on any sandbox.
Seems to be a known issue that was fixed recently in Winter 16 patch 9.  However, it's still affecting all my sandboxes.

This is the error while running any simple anonymous apex:
UNKNOWN ERROR: SOAP-ERROR: Encoding: object has no 'uiRequestId' property

SFDC Known issue:
https://success.salesforce.com/issues_view?id=a1p300000008a6HAAQ

**Comment by diligent176** [comment]
The same anonymous apex works against production (NA12 in my case).

**Comment by diligent176** [comment]
![image](https://cloud.githubusercontent.com/assets/7737939/10794621/f45d8bca-7d52-11e5-8c10-55cbbf6e4f3f.png)

**Comment by ryanbrainard** [comment]
This should have been fixed in [v34.0.8](https://github.com/ryanbrainard/forceworkbench/releases/tag/34.0.8).

**Comment by diligent176** [comment]
The issue is still happening in workbench 34.0.8 when API selected is 35.
![image](https://cloud.githubusercontent.com/assets/7737939/10801639/94319426-7d75-11e5-8c12-da4b831f7350.png)

If I close the browser session, start it all back up and then launch workbench on API 34, it works.

**Comment by gmathrubootham** [comment]
The issue is still happening since apex wsdl was not updated as part of the original fix.  Also, we need to invalidatate wsdl cache to prevent the old wsdl from getting read.  I have a pull request which should take care of both issues - https://github.com/ryanbrainard/forceworkbench/pull/668

Re-opening this.  This will be fixed once my pull request is merged in.
